config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @user = current_user
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Tentang</h1>
<p>
 

web ini dibuat untuk penelitian dan sarana berbagi informasi yang bermanfaat serta menjadi pembelajaran bagi orang - orang yang mau belajar bahasa pemrograman ruby on rails
   
   </p>
            

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Kontak</h1>
<p>
 

   <%= link_to image_tag("fb.png", alt: "Rails logo"),
              'https://www.facebook.com/' %> <a href="https://www.facebook.com/jimmy.dbajo?fref=ts"><em>jimmy.dbajo@yahoo.com</em></a>  
   <%= link_to image_tag("twt.png", alt: "Rails logo"),
              'https://twitter.com/' %> <a href="https://twitter.com/renogumi"><em>@renogumi</em></a>
   <%= link_to image_tag("wa.png", alt: "Rails logo"),
   'https://web.whatsapp.com/' %> <a href="https://web.whatsapp.com/"><em>089673314797</em></a>  
   
   </p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Bantuan</h1>
<p>
 cara penggunaan web ini sebagai berikut :
 1.ssfddfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
 
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Postingan</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

<header>
   <div align="center">
 

    <h1>Selamat Datang di Sosmate</h1>
<h2>
 Terkadang informasi lebih berbahaya dari pada senjata, tergantung bagaimana cara kita menggunakannya.
</h2>

    <h3>
     4IA15 FTI
     
    </h3>

    <%= link_to "Daftar Sekarang!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>

  <%= link_to image_tag("S.png", alt: "Rails logo"),
              'https://asooy-tanbak37.c9.io/' %>
<% end %>